daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
  - enhancement
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
closeComment: >
  This issue has been automatically closed due to inactivity.
# Updated Sun Nov  9 12:49:17 CET 2025
# Updated Sun Nov  9 12:52:43 CET 2025
