name: Build Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build documentation site
        run: |
          mkdir -p docs-site
          cp README.md docs-site/
          cp -r modules docs-site/ 2>/dev/null || true
          cp -r labs docs-site/ 2>/dev/null || true
          cp -r docs docs-site/ 2>/dev/null || true
          echo "Documentation built successfully"
          
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs-site/